//! vLLM-compatible `sha256_cbor` prefix-cache block hashing.
//!
//! The supported first-iteration contract is deliberately narrow: normal
//! dense attention, no LoRA/multimodal/cache-salt extra keys, and a fixed
//! `PYTHONHASHSEED` value supplied as an unsigned integer. vLLM hashes the
//! decimal seed string for the initial parent, then hashes the canonical CBOR
//! value `(parent_hash, tuple(token_ids), None)` for each complete block.

use sha2::{Digest, Sha256};

/// Full SHA-256 hash published by current vLLM KV Events.
pub type BlockHash = [u8; 32];

#[derive(Debug, Clone)]
pub struct BlockKeyGenerator {
    block_size: usize,
    none_hash: BlockHash,
}

impl BlockKeyGenerator {
    pub fn new(block_size: usize, hash_seed: u64) -> Self {
        assert!(block_size > 0, "block_size must be greater than zero");
        let seed = hash_seed.to_string();
        let mut encoded_seed = Vec::with_capacity(seed.len() + 2);
        encode_major(&mut encoded_seed, 3, seed.len() as u64);
        encoded_seed.extend_from_slice(seed.as_bytes());

        Self {
            block_size,
            none_hash: digest(&encoded_seed),
        }
    }

    pub fn block_size(&self) -> usize {
        self.block_size
    }

    /// Return one key per complete block. A trailing partial block is not
    /// cache-addressable and is intentionally omitted.
    pub fn generate_block_keys(&self, token_ids: &[u32]) -> Vec<BlockHash> {
        let mut parent = self.none_hash;
        token_ids
            .chunks_exact(self.block_size)
            .map(|tokens| {
                parent = hash_block(&parent, tokens);
                parent
            })
            .collect()
    }

    #[cfg(test)]
    pub(crate) fn none_hash(&self) -> BlockHash {
        self.none_hash
    }
}

fn hash_block(parent: &BlockHash, token_ids: &[u32]) -> BlockHash {
    let mut encoded = Vec::with_capacity(40 + token_ids.len() * 3);

    // Canonical CBOR for: [parent_hash_bytes, [token ids...], null]
    encode_major(&mut encoded, 4, 3);
    encode_major(&mut encoded, 2, parent.len() as u64);
    encoded.extend_from_slice(parent);
    encode_major(&mut encoded, 4, token_ids.len() as u64);
    for &token_id in token_ids {
        encode_major(&mut encoded, 0, u64::from(token_id));
    }
    encoded.push(0xf6);

    digest(&encoded)
}

fn encode_major(output: &mut Vec<u8>, major: u8, value: u64) {
    debug_assert!(major <= 7);
    let prefix = major << 5;
    match value {
        0..=23 => output.push(prefix | value as u8),
        24..=0xff => {
            output.push(prefix | 24);
            output.push(value as u8);
        }
        0x100..=0xffff => {
            output.push(prefix | 25);
            output.extend_from_slice(&(value as u16).to_be_bytes());
        }
        0x1_0000..=0xffff_ffff => {
            output.push(prefix | 26);
            output.extend_from_slice(&(value as u32).to_be_bytes());
        }
        _ => {
            output.push(prefix | 27);
            output.extend_from_slice(&value.to_be_bytes());
        }
    }
}

fn digest(bytes: &[u8]) -> BlockHash {
    Sha256::digest(bytes).into()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn from_hex(value: &str) -> BlockHash {
        assert_eq!(value.len(), 64);
        let mut output = [0_u8; 32];
        for (index, byte) in output.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&value[index * 2..index * 2 + 2], 16).unwrap();
        }
        output
    }

    #[test]
    fn sha256_cbor_matches_independent_vllm_goldens() {
        let generator = BlockKeyGenerator::new(128, 0);
        assert_eq!(
            generator.none_hash(),
            from_hex("4e1195df020de59e0d65a33a4279f1183e7ae4e5d980e309f8b55adff2e61c3e")
        );

        let tokens: Vec<u32> = (0..256).collect();
        assert_eq!(
            generator.generate_block_keys(&tokens),
            vec![
                from_hex("41b04e727e2efe6a5e35a707a47e3e11872b3215e1056d068d9bde11d7e22ce7"),
                from_hex("ad8f0385e9091ed10027f18191a8d1e7935ed4a2bf1768f047380def604d3987"),
            ]
        );
    }

    #[test]
    fn sha256_cbor_matches_python_integer_boundaries_and_seeds() {
        #[derive(serde::Deserialize)]
        struct OracleCase {
            seed: u64,
            none_hash: String,
            block_hashes: Vec<String>,
        }
        #[derive(serde::Deserialize)]
        struct Oracle {
            algorithm: String,
            cbor2_version: String,
            block_size: usize,
            token_ids: Vec<u32>,
            trailing_partial_tokens: usize,
            cases: Vec<OracleCase>,
        }

        // Generated by Python cbor2 5.6.5, not by this encoder. The fixture
        // also records each canonical-CBOR input for representation review.
        let oracle: Oracle = serde_json::from_str(include_str!(
            "../../tests/fixtures/kv_cbor/python_oracle.json"
        ))
        .unwrap();
        assert_eq!(oracle.algorithm, "sha256_cbor");
        assert_eq!(oracle.cbor2_version, "5.6.5");
        assert_eq!(oracle.block_size, 16);
        assert_eq!(oracle.token_ids.len(), 35);
        assert_eq!(oracle.trailing_partial_tokens, 3);
        assert_eq!(
            oracle
                .cases
                .iter()
                .map(|case| case.seed)
                .collect::<Vec<_>>(),
            [0, 42]
        );
        for case in oracle.cases {
            let generator = BlockKeyGenerator::new(oracle.block_size, case.seed);
            assert_eq!(generator.none_hash(), from_hex(&case.none_hash));
            let expected: Vec<_> = case
                .block_hashes
                .iter()
                .map(|hash| from_hex(hash))
                .collect();
            assert_eq!(expected.len(), 2);
            assert_eq!(
                generator.generate_block_keys(&oracle.token_ids),
                expected,
                "canonical-CBOR boundaries and hash chain for seed {}",
                case.seed
            );
            assert_eq!(
                generator.generate_block_keys(&oracle.token_ids[..32]),
                expected,
                "trailing partial tokens must not alter complete block hashes"
            );
        }
    }

    #[test]
    fn trailing_partial_block_is_not_hashed() {
        let generator = BlockKeyGenerator::new(16, 0);
        assert!(generator.generate_block_keys(&[1; 15]).is_empty());
        assert_eq!(generator.generate_block_keys(&[1; 31]).len(), 1);
    }
}
